In [1]:
import numpy as np

In [2]:
def get_line_by_two_points(x, y):
    l = np.cross(x, y)
    norm = np.linalg.norm(np.array([l[0], l[1]]))
    return l / norm

In [3]:
def get_point_by_two_lines(l1, l2):
    ray = np.cross(l1, l2)
    return ray / ray[2]

In [4]:
p1 = np.array([0, 1, 1])
p2 = np.array([1, 1, 1])
p3 = np.array([0, 2, 1])
p4 = np.array([1, 2, 1])

In [5]:
l1 = get_line_by_two_points(p1, p2)
l2 = get_line_by_two_points(p3, p4)

In [25]:
l1

array([ 0.,  1., -1.])

In [26]:
l2

array([ 0.,  1., -2.])

In [7]:
np.cross(l1, l2)

array([-1.,  0.,  0.])